services:
  sonarqube:
    image: sonarqube:community
    container_name: school-admin-sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
    networks:
      - school-admin-network

volumes:
  sonar_data:
  sonar_logs:
