sonar.projectKey=kibi-backend
sonar.projectName=Kibi Backend

sonar.sources=app
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=\
  vendor/**,\
  node_modules/**,\
  bootstrap/**,\
  storage/**,\
  public/**,\
  database/**,\
  config/**,\
  resources/**

sonar.coverage.exclusions=\
  app/Console/**,\
  app/Exceptions/**,\
  app/Providers/**
